---
title: "Multivariate Analysis Project Proposal"
author: "Group 4"
date: "8 March 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1.	Background to data set – why is this an interesting data set?
In this analysis the popculture/imdb-5000-movie-dataset from the data.world repository has been used  (https://data.world/popculture/imdb-5000-movie-dataset/workspace/file?filename=movie_metadata.csv%2Fmovie_metadata.csv). The dataset was created by Chuan Sun (@sundeepblue on Github) who "scraped tons of metadata using a combination of www.the-numbers.com, IMDB.com, and a Python library called "scrapy". He was able to obtain 28 variables for 5043 movies and 4906 posters (998MB), spanning across 100 years in 66 countries. There are 2399 unique director names, and thousands of actors/actresses." (reference)

##2.	Why is it a multivariate data set?

##3.	General aim of the future multivariate analysis (not set in stone!)
<<<<<<< HEAD
||||||| merged common ancestors
Due to the increasing popularity of social platforms, the social media campaign has now become an important marketing tactic in the movie industry. Previous research, such as Pardo’s paper (2013), found that social media has a great impact on movie qualitatively. In this study, we aim to investigate the quantitative relationship between social media and movie performance such as box office and movie ratings.

##Reference List  
Pardo, A., 2013. Digital Hollywood: How Internet and Social media are changing the movie business. In Handbook of Social Media Management (pp. 327-347). Springer, Berlin, Heidelberg.
=======
Due to the increasing popularity of social platforms, the social media campaign has now become an important marketing tactic in the movie industry. Previous research, such as Pardo’s paper (2013), found that social media has a great impact on movie qualitatively. In this study, we aim to investigate the quantitative relationship between social media and movie performance such as box office and movie ratings.

Our second general aim would be to investigate the relationship among film box office grosses, budget and the county of origin. Hollywood’s stereotypes seemingly dominate in reality, while most films around the world are produced from English-speaking countries. In the wave of globalisation and with the popularity of social media nowadays, we wish to question if cultural diversity in film industry still exists as in other forms of arts. Regarding inter-country, or in a broader sense, inter-continent cultural difference, we think that a principle component or cluster analysis would be a good starting point. The characteristics of the mainstream film in various countries should reflect the colour of their culture. We also would like to have a glimpse into the niche markets for film industry. These films of interest could be non-mainstream, low-budget or independent film. We would examine if these films could satisfy specific market needs. 

##Reference List  
Pardo, A., 2013. Digital Hollywood: How Internet and Social media are changing the movie business. In Handbook of Social Media Management (pp. 327-347). Springer, Berlin, Heidelberg.
>>>>>>> ad96ce3aa3607b851a09611e5996ef9967c79280

Note:  
- No need to specify concrete statistical methods (yet!)  
- Not more than 1-2 pages  
- One proposal per group  

